language: python
python:
  - 2.6
install:
  - sudo apt-get install -y build-essential python-profiler
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg
script: bin/test -s niteoweb.click2sell

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com