language: python
python:
  - 2.6
install:
  - sudo apt-get install -y build-essential
  - python bootstrap.py -c development.cfg
  - bin/buildout -c development.cfg -vvvv
script: bin/test -s niteoweb.click2sell

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com