language: python
python:
  - 2.6
install:
  - sudo apt-get purge python2.5
  - sudo apt-get install -y python-profiler build-essential
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg
script: bin/test -s niteoweb.click2sell

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com